name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your default branch if not 'main'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Replace with your Node.js version

      # Install dependencies and build the app
      - name: 'Install dependencies'
        run: |
          npm install
          npm run build # If your app has a build step; otherwise, remove this line

      # Archive the app
      - name: 'Archive files'
        run: zip -r app.zip .

      # Deploy the app to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<Your-App-Service-Name>'  # Replace with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './app.zip'
